"""Generate the Devpost submission text from docs/devpost-writeup.md.

The writeup is the checked source (every figure cited, see
tools/check_doc_numbers.py); this only maps it onto Devpost's form fields and
drops the citation comments, so the two can never disagree.

    uv run python tools/devpost_export.py      # -> docs/devpost-submission.md
"""

from __future__ import annotations

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]

#: Devpost "Built with" tags (limit 25), each a technology the project uses.
BUILT_WITH = [
    "opencv", "python", "onnx", "yolox", "aws", "aws-cdk", "aws-batch", "aws-fargate",
    "aws-step-functions", "aws-lambda", "amazon-dynamodb", "amazon-s3", "amazon-cloudfront",
    "amazon-ecr", "aws-graviton", "amazon-ec2", "amazon-bedrock", "claude",
    "model-context-protocol", "amazon-cloudwatch", "aws-x-ray", "next.js", "typescript",
    "cool-cloud-optimized-opencv", "uv",
]

LINKS = {
    "Report viewer (live, no login)": "https://d18du1w0ii5yhw.cloudfront.net/",
    "Code (MIT)": "https://github.com/Kim-Hakseong/blindspot",
    "Video (3:45, unlisted)": "https://youtu.be/QwyEL-QrRqk",
}


def _sections(md: str) -> dict[str, str]:
    parts = re.split(r"^## (.+)$", md, flags=re.M)
    return {parts[i].strip(): parts[i + 1].strip() for i in range(1, len(parts), 2)}


def export(md: str) -> str:
    md = re.sub(r"\s*<!--.*?-->", "", md, flags=re.S)
    s = _sections(md)
    get = lambda prefix: next(v for k, v in s.items() if k.startswith(prefix))  # noqa: E731
    accomplishments = get("Results") + "\n\n**Known limitations**\n\n" + get("Known limitations")
    fields = [
        ("Inspiration", get("Inspiration")),
        ("What it does", get("What it does")),
        ("How I built it", get("How I built it")),
        ("Challenges I ran into", get("Challenges")),
        ("Accomplishments that I'm proud of", accomplishments),
        ("What I learned", get("What I learned")),
        ("What's next for Blindspot", get("What's next")),
    ]
    out = [f"## {name}\n\n{body}\n" for name, body in fields]
    out.append("## Built with\n\n" + ", ".join(BUILT_WITH) + "\n")
    out.append("## Links\n\n" + "\n".join(f"- {k}: {v}" for k, v in LINKS.items()) + "\n")
    return "\n".join(out)


def main() -> int:
    text = export((ROOT / "docs" / "devpost-writeup.md").read_text(encoding="utf-8"))
    header = ("<!-- Generated by tools/devpost_export.py from docs/devpost-writeup.md; "
              "edit the writeup, not this file. -->\n\n")
    (ROOT / "docs" / "devpost-submission.md").write_text(header + text, encoding="utf-8")
    print(f"docs/devpost-submission.md: {len(text)} characters, {len(BUILT_WITH)} Built-with tags")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
